/**
 * Metadata that lives in the database — deliberately storage agnostic.
 * Never store a Telegram file_id, R2 URL, etc. directly here; that lives
 * behind storageProvider + storageKey/thumbnailKey, resolved on read via
 * the active StorageProvider.
 */
export interface VideoMetadata {
  id: string;
  title: string;
  description?: string;
  hashtags: string[];
  category: string;
  language?: string;
  duration: number; // seconds
  width: number;
  height: number;
  uploader: string;
  uploadDate: number;
  views: number;
  likes: number;
  comments: number;
  shares: number;

  storageProvider: string;
  storageKey: string;
  thumbnailKey?: string;
  qualities?: Record<string, string>;

  /**
   * Per-quality HLS variant playlist text, generated by the transcoder
   * with `-hls_flags single_file`. Each playlist references its single
   * media file via EXT-X-BYTERANGE and contains a "{{STREAM_URL}}"
   * placeholder in place of the real filename — HlsController swaps that
   * for the actual /stream?key=... URL at request time, since the real
   * storageKey (Telegram file_id etc.) isn't known until upload completes.
   */
  hlsPlaylists?: Record<string, string>;

  /** Static per-quality bandwidth/resolution used to build the
   *  EXT-X-STREAM-INF lines in the master playlist. */
  qualityMeta?: Record<string, { bandwidth: number; width: number; height: number }>;
}

export type CreateVideoMetadata = Omit<
  VideoMetadata,
  "id" | "views" | "likes" | "comments" | "shares" | "uploadDate"
> & { uploadDate?: number };

/** Provider-independent shape returned to API clients. Clients must never
 *  learn whether the bytes live in Telegram, R2, or Supabase. */
export interface ClientVideoView {
  id: string;
  title: string;
  description?: string;
  hashtags: string[];
  category: string;
  language?: string;
  duration: number;
  width: number;
  height: number;
  uploader: string;
  uploadDate: number;
  views: number;
  likes: number;
  comments: number;
  shares: number;
  videoUrl: string;
  thumbnailUrl: string;
  qualities?: Record<string, string>;
  /** Bandwidth/resolution per quality label — safe to expose as-is (no
   *  storage keys), used client-side to match hls.js levels to labels
   *  in the manual quality picker. Present only once HLS renditions
   *  exist for the video. */
  qualityMeta?: Record<string, { bandwidth: number; width: number; height: number }>;
  /** True once at least one HLS rendition exists, so the client knows
   *  whether to attach hls.js at /hls/master or fall back to videoUrl. */
  hasHls?: boolean;
}

export interface UploadVideoResult extends ClientVideoView {
  ownerToken: string;
}
